# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'TrailTasks' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'TrailTasksTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(RCT-Folly-RCT-Folly_privacy React-Core-React-Core_privacy)

      if targets_to_ignore.include? target.name
          target.remove_from_project
      end
        # 1. Completely remove RCT-Folly_privacy.bundle outputs
      if target.name == 'RCT-Folly' || target.name.include?('RCT-Folly')
        target.build_phases.each do |phase|
          next unless phase.respond_to?(:files)
          phase.files.each do |file|
            if file.display_name.include?('RCT-Folly_privacy.bundle')
              phase.remove_file_reference(file.file_ref)
            end
          end
        end
      end
        # 2. Also remove the React-Core-RCTI18nStrings target if needed
      if target.name == "React-Core-RCTI18nStrings"
        target.remove_from_project
      end
    end
  end
end

# Uncomment this line if you're not using auto-linking or if auto-linking causes trouble
# pod 'WatermelonDB', path: '../node_modules/@nozbe/watermelondb'

# WatermelonDB dependency, should not be needed on modern React Native
# (please file an issue if this causes issues for you)
# pod 'React-jsi', path: '../node_modules/react-native/ReactCommon/jsi', modular_headers: true

# WatermelonDB dependency
pod 'simdjson', path: '../node_modules/@nozbe/simdjson', modular_headers: true
pod 'react-native-config', :path => '../node_modules/react-native-config'

