import { Addon, User_Session } from "../watermelon/models";
export interface SessionCfg {
  session: User_Session | null;
  sessionId: string;
  userId: string;
  type: string;
  sessionDescription?: string;
  sessionName: string;
  completedTrails: number;
  sessionCategory: [string, string];
  distanceNeeded: number;
  currentTrailDistance: number;
  totalSets: number;
  focusTimeSec: number;
  shortBreakSec: number;
  longBreakSec: number;
  autoContinue: boolean;
  currentPaceMph?: number;
  minPaceMph?: number;
  maxPaceMph?: number;
  paceIncreaseValueMph?: number;
  paceIncreaseIntervalSec?: number;
  tokenBonusFlat?: number;
  tokenBonusPercent?: number;
  backpack: { addon: Addon | null; minimumTotalMiles: number }[];
}
export interface JoinedUserTrail {
  _changed: string;
  _status: string;
  created_at: number;
  email: string;
  first_name: string;
  id: string;
  last_name: string;
  park_id: string;
  park_name: string;
  park_type: string;
  password: string;
  push_notifications_enabled: boolean;
  theme_preference: string;
  trail_difficulty: string;
  trail_distance: string;
  trail_elevation: number;
  trail_id: string;
  trail_image_url: string;
  trail_lat: string;
  trail_long: string;
  trail_name: string;
  trail_progress: string;
  trail_started_at: string;
  updated_at: number;
  username: string;
}

export type SessionCateegories = {
  1: "Chores";
  2: "Cooking";
  3: "Crafts";
  4: "DIY Project";
  5: "Drawing";
  6: "Driving";
  7: "Errands";
  8: "Family";
  9: "Finance";
  10: "Gaming";
  11: "Gardening";
  12: "Gym";
  13: "Hiking";
  14: "Learning";
  15: "Meditating";
  16: "Music";
  17: "Other";
  18: "Outdoors";
  19: "Personal Projects";
  20: "Pets";
  21: "Photography";
  22: "Planning";
  23: "Reading";
  24: "Self Care";
  25: "Social";
  26: "Sports";
  27: "Study";
  28: "Work";
  29: "Workout";
  30: "Writing";
  31: "Volunteering";
  32: "Yoga";
};
